### ISSUE TITLE
Can't buy or sell anything and the money dissapears

### ISSUE THREAD

**Issue by ilore** [Rughalt/d35e-loot-sheet-npc#24]
When a PC tries to buy or sell something from a merchant, nothing happens, the item doesn't appear in the PCs inventory, the number of items in the shop doesn't change and the worst is that all the money in the PCs inventory dissapears (only when he tries to buy something).

One of the pictures shows the PC configuration, the second shows the merchant configuration. I'm using FVTT 0.8.6 only with 3.5 Loot Sheet NPC 2.0.4.

![Player-Character](https://user-images.githubusercontent.com/32924279/121804703-06e03280-cc48-11eb-96e6-f47467d79408.jpg)
![DungeonMaster](https://user-images.githubusercontent.com/32924279/121804721-0e074080-cc48-11eb-93c7-82a5974f6936.jpg)

**Comment by ilore** [comment]
The bug has changed, I don't now why: Now I can buy items, but the system buys all of them except the last one (if there are 10, it buys 9), the PC spents all the money doesn't matter the cost, the chat message says that the cost of the item was "NaN" and it doesn't matter the quantity of the items that the you have bought, you only receive one in your inventory.

**Comment by wmve** [comment]
i can confirm the last observation.

steps to reproduce

1. create NPC actor
2. change sheet to D35E.LootSheetD35ENPC
3. add 20 longswords from item browser, change name to add XX (to be unique)
4. add 50 daggers from item browser, change name to add XX (to be unique)
5. open player browser session
6. open character sheet
7. open loot sheet
8. select dagger on loot sheet
9. leave quantity at 1, click loot

expected results:
- player character sheet currency will be reduced by 2 gp
- loot sheet "Dagger XX" quantity will be reduced from 50 to 49

actual results:
- all player character sheet currency has been removed
- loot sheet "Dagger XX" quantity is reduced from 50 to 0

on DM console:
![SNAG-0167](https://user-images.githubusercontent.com/55966777/125179606-b95ed300-e1bd-11eb-96b3-9eefac5f9b54.png)

on player console:
![SNAG-0168](https://user-images.githubusercontent.com/55966777/125179608-c11e7780-e1bd-11eb-8016-afae74a9151e.png)
![SNAG-0169](https://user-images.githubusercontent.com/55966777/125179610-c380d180-e1bd-11eb-86ad-10be3c8573f0.png)
![SNAG-0175](https://user-images.githubusercontent.com/55966777/125179816-178cb580-e1c0-11eb-8546-35b6ed2c1151.png)

on DM console after:
![SNAG-0171](https://user-images.githubusercontent.com/55966777/125179615-d8f5fb80-e1bd-11eb-90f4-ffac598db856.png)

versions:
![SNAG-0172](https://user-images.githubusercontent.com/55966777/125179617-de534600-e1bd-11eb-9f74-81be8aa2ea8e.png)
![SNAG-0173](https://user-images.githubusercontent.com/55966777/125179618-e14e3680-e1bd-11eb-8f0c-eb1d6871eb27.png)

actor loot sheet and character sheet afterward
[fvtt-Actor-loot-test.zip](https://github.com/Rughalt/d35e-loot-sheet-npc/files/6796149/fvtt-Actor-loot-test.zip)
