### ISSUE TITLE
changing from loot sheet to merchant and back again

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/d35e-loot-sheet-npc#26]
Once a npc is converted to a loot sheet and then to a merchant, you can not go back to a loot sheet.
![Loot bug](https://user-images.githubusercontent.com/73614995/127797672-6bad82c7-a4bd-4753-9c40-a01b105c5828.gif)

**Comment by Axecleft** [comment]
When changing the npc to a merchant it will not save this setting and will revert to a loot sheet with a world restart.

**Comment by Rughalt** [comment]
Fixed by merging code from upstream.
