### ISSUE TITLE
Using roll tables is not working and throwing an error

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/d35e-loot-sheet-npc#27]
When using a roll table to populate a merchant, the sheet is throwing an error.

![image](https://user-images.githubusercontent.com/73614995/129615979-f94a18b9-30fa-4e36-8925-028050e4d179.png)

![image](https://user-images.githubusercontent.com/73614995/129616040-13afcefb-4128-4a1f-bca3-e6c14b46ef49.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 2.2.0
