### ISSUE TITLE
no gem icons show on loot sheet for players

### ISSUE THREAD

**Issue by wmve** [Rughalt/d35e-loot-sheet-npc#28]
steps to recreate (used my demo world where only module active is lootsheet)

1. [in DM console] create new npc actor
2. add npc to map
3. switch to loot sheet
4. add adamantine battle axe
5. check "enable dragging"
6. add permissions for some existing pc
7. [in player console that has permission to lootsheet] open lootsheet

expected behaviour: see blue gem buttons on right side of lootsheet that allow player to loot items
actual behaviour: blue gem buttons do not appear

expected behaviour: should be able to drag items from loot sheet to pc sheet
actual behaviour: can't drag items from loot sheet to pc sheet

![image](https://user-images.githubusercontent.com/55966777/133343366-b8b69f9a-9a65-46c0-b823-c4aee1284b25.png)

**Comment by wmve** [comment]
yes, i checked that the character i'm using is a PC.  (it has a summary tab.)

**Comment by wmve** [comment]
i'm only able to drag stuff to PCs and NPCs as the DM, and then it only drags the entire pile (if quantity > 1).  so, there is a workaround, but it's clumsy.

**Comment by Rughalt** [comment]
Players must have (tick) permission - this allows them to grab items. View (eye) allows only looking at the loot.
