### ISSUE TITLE
Hitting Enter anywhere on the sheet asks if you want to convert to coins

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/d35e-loot-sheet-npc#7]
Hitting enter anywhere e.g. max load will prompt the convert to coin dialog

![convert](https://user-images.githubusercontent.com/22633854/105857483-3f0d0e80-5fe2-11eb-88f1-22f377d6cb69.gif)

**Comment by Rughalt** [comment]
Fixed, will be out in 1.1.0
