### ISSUE TITLE
Sheet contents don't resize vertically

### ISSUE THREAD

**Issue by agrtga** [Rughalt/d35e-loot-sheet-npc#9]
The window can resize horizontally and vertically, but the contents only resize horizontally. Additionally, the bottom of the contents can be cut off if resized small. That is, the minimum size needs to be increased so it doesn't get cut-off. There is an adequate minimum for the horizontal size.

The attached images show how the window gets taller, but the contents do not; and that the bottom gets cutoff when made too short (with no scrollbar).

<img width="304" alt="ex1" src="https://user-images.githubusercontent.com/12749451/107137448-bb54fb00-68da-11eb-8aba-097ba35df71c.png">
<img width="227" alt="ex2" src="https://user-images.githubusercontent.com/12749451/107137450-be4feb80-68da-11eb-87f8-9c1d02b471ed.png">

**Comment by Rughalt** [comment]
Fix will be out in 1.1.0
